name: Uzun SSH Erişimi (6 saat)

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 saat

    steps:
      - name: Tmate SSH başlat
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 360
        with:
          limit-access-to-actor: false
